### ISSUE TITLE
Request - allowing chaining after adding Brighter to ServiceCollection.

### ISSUE THREAD

**Issue by brainwipe** [dstockhammer/Paramore.Brighter.AspNetCore#1]
When adding in the services, there is no way to chain onto the end of the Brighter configuration. 

What I would like to do is break out of the builder using a `Services` property so that I can continue chaining like so:

    services
       .AddBrighter()
         .HandlersFromAssemblies(typeof(CreateFooHandler).Assembly)
         .Services
       .AddMvc();

**Comment by dstockhammer** [comment]
Makes sense, thanks for the contribution. Will get an RC2 release ready this evening :shipit:

**Comment by dstockhammer** [comment]
FYI, I've also added the same functionality to Darker: https://github.com/BrighterCommand/Darker/commit/4269fb41b6ea3c1a9c6af41d2a3f90bd03d7ae57
