### ISSUE TITLE
Discussion - Use GetTypes() rather than GetExportedTypes()

### ISSUE THREAD

**Issue by brainwipe** [dstockhammer/Paramore.Brighter.AspNetCore#2]
This one is somewhat tenuous as a request. I'm unsure if this is a use case that is "just me" or generally reasonable.

In [HandlersFromAssemblies](https://github.com/dstockhammer/Paramore.Brighter.AspNetCore/blob/d7977401bfc7dbec59a02ccab1a8c3afd7088d11/src/Paramore.Brighter.AspNetCore/AspNetHandlerBuilder.cs#L52) it only retrieves public types. I would like it to find Handlers marked as `internal` too.

In the application architecture I have, each DLL is responsible for adding to the `IServiceCollection` itself. So when `services.AddBrighter().HandlersFromAssemblies()` is called, it is doing so from within the same DLL as the Handlers are in. Therefore, I would like to make the Handlers `internal` while keeping the Commands `public`.

My justification is that Service Collection is actually a MS DI Extension and not part of the ASPNET namespace (as it used to be), so it's fine for each DLL to manage its own DI and keep the concrete types `internal` with the interface `public`.

I appreciate that in many architectural styles, the Service Collection is only found in the API project and so the Handlers must `public` for them to be registered. 

I'm going to have a play on my fork to see the effect of changing that line!

**Comment by dstockhammer** [comment]
Yeah, makes sense. I wonder if there is value in making this configurable and default to `GetTypes()`?
I only used `GetExportedTypes()` because I copied the code from Darker. Unfortunately in Darker, internal handlers are not supported because it has to use dynamic to dispatch queries.

Would you mind creating a PR for this? I'm quite busy at the moment and won't get to do any OSS work this week :(

**Comment by brainwipe** [comment]
Would love to help. I'll get on that tomorrow (UK). I'm using Brighter (and Darker) for the next gen product at @MyClinicalOutcomes and so very happy to find I don't have to write a CQRS library again!

I'm not halted by this or #1, so please don't rush a new release out.

**Comment by dstockhammer** [comment]
Alright, thanks! Will hold off with next release until we can get your PR in.
