### ISSUE TITLE
Problems with version 1.0.0 and Brighter 7.3.15

### ISSUE THREAD

**Issue by DejanMilicic** [dstockhammer/Paramore.Brighter.AspNetCore#8]
I have a project where I was using
Paramore.Brighter.AspNetCore 1.0.0-RC2
Paramore.Brighter 7.1.5

After upgrading nuget packages to
Paramore.Brighter.AspNetCore 1.0.0
Paramore.Brighter 7.3.15

I am now having following error reported by AddBrighter extension method

System.IO.FileLoadException: Could not load file or assembly 'Paramore.Brighter, Version=7.1.0.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

I tried restoring packages several times, deleting obj and bin folders as well as trying to locate where version 7.1.0.0 could be referenced, but without success.

Any idea what could be causing this problem and how to solve it?

**Comment by holytshirt** [comment]
Looks like you'll need to do a BindingsRedirect  for Brighter

**Comment by holytshirt** [comment]
I'll push an update for this lib

**Comment by DejanMilicic** [comment]
Also, a brief explanation on BindingsRedirect would be welcome 😁

**Comment by holytshirt** [comment]
@DejanMilicic I've done the pull request which brings it up to the latest version. So you won't have dll hell, I thought dotnet core projects worked this out for you, seems it  doesn't :/

**Comment by dstockhammer** [comment]
https://www.nuget.org/packages/Paramore.Brighter.AspNetCore/1.0.11

**Comment by holytshirt** [comment]
Thanks @dstockhammer!
